### ISSUE TITLE
Api documentation

### ISSUE THREAD

**Issue by frechina** [Payum/PayumServer#46]
Hi,

I've been wondering if there is some documentation about how to use the PayumServer API. I've been playing with the code and after solving some issues I'm stuck adding gateways. Any help? I wanted to add stripe and paypal.

Thank you

**Comment by makasim** [comment]
There is a js client for the server (which uses it api). https://github.com/Payum/PayumServerUI

You can start with it and see what requests it sends and what format.

The client is easy to do (especially if you gonna use docker image `payum/server-ui`. Once up and running go to settings and configure the server url to work with.
You can configure gateways there, purchase stuff, see payment details and so on. 

Once you have gateways configured you can open this small demo page.
https://github.com/Payum/PayumServer/blob/master/web/demo.html

It shows how the payment server could be integrated to your shop or app. 

Pay attention it is a proof of concept, there might be bugs (tell me if you find some) or missing features.

**Comment by makasim** [comment]
that's how I run it locally 

```
version: '2'
services:
  payum-server:
    image: payum/payum-server
    container_name: payum-server
    restart: always
    environment:
      - PAYUM_MONGO_URI=mongodb://mongo:27017/payum_server
      - PAYUM_DEBUG=1
      - VIRTUAL_HOST=payum-server.local
    links:
      - mongo
    volumes:
      - .:/payum

  payum-server-ui:
    image: payum/server-ui
    container_name: payum-server-ui
    restart: always
    environment:
      - VIRTUAL_HOST=payum-server-ui.local
    volumes:
      - ./PayumServerUI:/payum

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
```
